add mass operation for assign, unassign, take-leave, cancel-leave
AY2021S1-CS2103-F10-4/tp pull request #101
Opened 2020-10-25 13:59 UTC by sigmund-c

resolves #78 
Usage:
`assign s/1 w/1 Cashier w/2 Pilot w/3 Janitor`
`unassign s/2 w/1 w/2 w/3`

2020-10-26 14:42 UTC, wakululuu requested changes, later dismissed

2020-10-26 14:42 UTC, wakululuu commented on docs/DeveloperGuide.md
> + operations are supported to reduce the required number of command calls.
```suggestion
operations are supported to reduce the required number of command calls.
```

2020-10-26 14:42 UTC, wakululuu commented on docs/DeveloperGuide.md
> +CommandParser class, Mass operations uses `ParserUtil`'s `GetAllValues()` method, which parses the user input
```suggestion
`*CommandParser` class, mass operations uses the `ArgumentMultimap#getAllValues(Prefix)` method, which parses the user input 
```

2020-10-26 14:42 UTC, wakululuu commented on docs/DeveloperGuide.md
> +These operations consist of their own Command class and CommandParser class. In each of the supported
```suggestion
These operations consist of their own `*Command` class and `*CommandParser` class. In each of the supported 
```

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/AssignCommand.java
> -            + PREFIX_SHIFT + "SHIFT_INDEX (must be a positive integer) "
Perhaps keep this line with `(must be a positive integer)` instead of the suggested edit to keep the message consistent across all commands.

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/AssignCommand.java
> +            + PREFIX_WORKER_ROLE + "WORKER_INDEX ROLE\n"
```suggestion
            + "{" + PREFIX_WORKER_ROLE + "WORKER_INDEX (must be a positive integer) ROLE}...\n"
```
`...` would show that the params can be repeated multiple times. I believe there is currently no convention to group a set of command prefixes and params with whitespaces between them together but perhaps we could use `{ }`.

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/AssignCommand.java
> +    public static final String MESSAGE_ASSIGN_SUCCESS = "%d new assignment(s) added.";
Would be good to still see all the assignments added.

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/AssignCommand.java
> +            model.updateFilteredWorkerList(PREDICATE_SHOW_ALL_WORKERS);
I don't think there is a need to update after adding each assignment.

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/UnassignCommand.java
> +    public static final String MESSAGE_UNASSIGN_SUCCESS = "%d shift assignment(s) removed.";
Similar to `AssignCommand`, it would be good if all assignments removed can be shown.

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/AssignCommand.java
> +        for (WorkerRole workerRole: workerRoles) {
```suggestion
        for (WorkerRole workerRole : workerRoles) {
```

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/AssignCommand.java
> +        for (WorkerRole workerRole: workerRoles) {
```suggestion
        for (WorkerRole workerRole : workerRoles) {
```

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/UnassignCommand.java
> +        for (Index workerIndex: workerIndexes) {
```suggestion
        for (Index workerIndex : workerIndexes) {
```

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/UnassignCommand.java
> +        for (Index workerIndex: workerIndexes) {
```suggestion
        for (Index workerIndex : workerIndexes) {
```

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/UnassignCommand.java
> +            model.updateFilteredWorkerList(PREDICATE_SHOW_ALL_WORKERS);
Similar to `AssignCommand`, I don't think we need to update in the loop.

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/UnassignCommand.java
> +    public static final String MESSAGE_UNASSIGN_SUCCESS = "%d shift assignment(s) removed.";
Similar to `AssignCommand`, it would be good to list all the assignments removed.

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/model/assignment/WorkerRole.java
> +public class WorkerRole {
Personally, `WorkerRole` as a class name doesn't seem very intuitive. Maybe use `WorkerRoleAssignment` or `WorkerRolePair`. The others can chip in on this as well.

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/parser/AssignCommandParser.java
> +                    "AAAA"), ive);
Is this a typo?

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/TakeLeaveCommand.java
>              + PREFIX_WORKER + "WORKER_INDEX (must be a positive integer)\n"
```suggestion
            + "{" + PREFIX_WORKER + "WORKER_INDEX (must be a positive integer)}...\n"
```

2020-10-26 14:42 UTC, wakululuu commented on src/main/java/seedu/address/logic/commands/UnassignCommand.java
>              + PREFIX_WORKER + "WORKER_INDEX (must be a positive integer)\n"
```suggestion
            + "{" + PREFIX_WORKER + "WORKER_INDEX (must be a positive integer)}...\n"
```

2020-10-29 09:47 UTC, plosslaw commented on src/main/java/seedu/address/logic/commands/CancelLeaveCommand.java
> +            + "{" + PREFIX_WORKER + "WORKER_INDEX (must be a positive integer)}...\n"
To be consistent with other commands such as worker-add
```suggestion
            + "[" + PREFIX_WORKER + "WORKER_INDEX (must be a positive integer)]...\n"
```

2020-10-29 09:47 UTC, plosslaw commented on src/main/java/seedu/address/logic/commands/CancelLeaveCommand.java
> +            model.deleteAssignment(assignmentInModel);
```suggestion
            try {
                model.deleteAssignment(assignmentInModel);
            } catch (AssignmentNotFoundException ex) {
                throw new CommandException(MESSAGE_NO_ASSIGNMENT_FOUND);
            }
```

2020-10-29 09:47 UTC, plosslaw commented on src/main/java/seedu/address/logic/commands/TakeLeaveCommand.java
> +            + "{" + PREFIX_WORKER + "WORKER_INDEX (must be a positive integer)}...\n"
```suggestion
            + "[" + PREFIX_WORKER + "WORKER_INDEX (must be a positive integer)]...\n"
```

2020-10-29 09:47 UTC, plosslaw commented on src/main/java/seedu/address/logic/commands/UnassignCommand.java
> +            + "{" + PREFIX_WORKER + "WORKER_INDEX (must be a positive integer)}...\n"
```suggestion
            + "[" + PREFIX_WORKER + "WORKER_INDEX (must be a positive integer)]...\n"
```

2020-10-29 10:15 UTC, plosslaw approved these changes
LGTM

2020-10-29 10:21 UTC, merged